const products = {
  products: [
    {
      name: "MSI RTX 3080 Gaming Trio Z 12GB",
      description: "",
      brand: "",
      price: 1250,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005920878_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005920878_1.jpg",
      category: "",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 45,
    },

    {
      name: 'Apple MacBook M1 Pro 16"',
      description: "",
      brand: "",
      price: 2750,
      countStock: 6,
      image: "https://media.materiel.net/r150/products/MN0005902616_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005902616_1.jpg",
      category: "",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 46,
    },
    {
      name: "New Product Items Name",
      description: "",
      brand: "",
      price: 458,
      countStock: 10,
      image:
        "https://media.ldlc.com/r150/ld/products/00/05/96/17/LD0005961723.jpg",
      category: "",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 47,
    },
    {
      name: "New Product Items Name",
      description: "",
      brand: "",
      price: 4984,
      countStock: 10,
      image:
        "https://media.ldlc.com/r150/ld/products/00/05/96/16/LD0005961662.jpg",
      category: "",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 48,
    },
    {
      name: "Best Selling Items Name",
      description: "",
      brand: "",
      price: 188,
      countStock: 10,
      image: "https://media.materiel.net/r250/products/MN0005792349_1.jpg",
      category: "",
      type: "",
      bestSelling: true,
      newProduct: false,
      id: 49,
    },
    {
      name: "Best Selling Items Name",
      description: "",
      brand: "",
      price: 234,
      countStock: 10,
      image: "https://media.materiel.net/r250/products/MN0005594909_1.jpg",
      category: "",
      type: "",
      bestSelling: true,
      newProduct: false,
      id: 50,
    },
    {
      name: "Best Selling Items Name",
      description: "",
      brand: "",
      price: 999,
      countStock: 10,
      image: "https://media.materiel.net/r250/products/MN0005717278_1.jpg",
      category: "",
      type: "",
      bestSelling: true,
      newProduct: false,
      id: 51,
    },
    {
      name: "Best Selling Items Name",
      description: "",
      brand: "",
      price: 555,
      countStock: 10,
      image:
        "https://media.materiel.net/r250/products/MN0005693354_1_0005764724_0005764757_0005764765.jpg",
      category: "",
      type: "",
      bestSelling: true,
      newProduct: false,
      id: 52,
    },
  ],
};

module.exports = products;
