const products = {
  products: [
    // Carte Graphique
    {
      name: "MSI RTX 3060 Ti Ventus 10GB",
      description: "",
      brand: "",
      price: 500,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005849576_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005849576_1.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: false,
      id: 1,
    },
    {
      name: "Gigabyte RTX 3070 10GB",
      description: "",
      brand: "",
      price: 700,
      countStock: 10,
      image:
        "https://media.materiel.net/r150/products/MN0005742518_1_0005853860.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005742518_1_0005853860.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: false,
      id: 2,
    },
    {
      name: "MSI RTX 3080 Gaming Trio Z 12GB",
      description: "",
      brand: "",
      price: 1250,
      countStock: 0,
      image: "https://media.materiel.net/r150/products/MN0005920878_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005920878_1.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: false,
      id: 3,
    },
    {
      name: "MSI RTX 3090 Ti Suprim X 24GB",
      description: "",
      brand: "",
      price: 2250,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005945170.jpg",
      imageDetails: "https://media.materiel.net/r550/products/MN0005945170.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 4,
    },
    {
      name: "MSI RTX 3060 Ti Ventus 10GB",
      description: "",
      brand: "",
      price: 500,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005849576_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005849576_1.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: false,
      id: 1,
    },
    {
      name: "Gigabyte RTX 3070 10GB",
      description: "",
      brand: "",
      price: 700,
      countStock: 10,
      image:
        "https://media.materiel.net/r150/products/MN0005742518_1_0005853860.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005742518_1_0005853860.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: false,
      id: 2,
    },
    {
      name: "MSI RTX 3080 Gaming Trio Z 12GB",
      description: "",
      brand: "",
      price: 1250,
      countStock: 0,
      image: "https://media.materiel.net/r150/products/MN0005920878_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005920878_1.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 3,
    },
    {
      name: "MSI RTX 3090 Ti Suprim X 24GB",
      description: "",
      brand: "",
      price: 2250,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005945170.jpg",
      imageDetails: "https://media.materiel.net/r550/products/MN0005945170.jpg",
      category: "carte-graphique",
      type: "",
      bestSelling: false,
      newProduct: false,
      id: 4,
    },
    // Carte Mere
    {
      name: "MSI MPG Z690 FORCE WIFI",
      description: "",
      brand: "",
      price: 500,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005899450_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005899450_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 5,
    },
    {
      name: "Asus ROG Crosshair VIII Dark Hero",
      description: "",
      brand: "",
      price: 650,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005851487_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005851487_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: false,
      newProduct: true,
      id: 6,
    },
    {
      name: "Asus ROG Crosshair VIII Formula",
      description: "",
      brand: "",
      price: 750,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005900771_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005900771_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 7,
    },
    {
      name: "Asus ROG MAXIMUS Z690 EXTREME GLACIAL",
      description: "",
      brand: "",
      price: 2100,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005901098_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005901098_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 8,
    },
    {
      name: "MSI MPG Z690 FORCE WIFI",
      description: "",
      brand: "",
      price: 500,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005899450_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005899450_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 5,
    },
    {
      name: "Asus ROG Crosshair VIII Dark Hero",
      description: "",
      brand: "",
      price: 650,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005851487_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005851487_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 6,
    },
    {
      name: "Asus ROG Crosshair VIII Formula",
      description: "",
      brand: "",
      price: 750,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005900771_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005900771_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 7,
    },
    {
      name: "Asus ROG MAXIMUS Z690 EXTREME GLACIAL",
      description: "",
      brand: "",
      price: 2100,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005901098_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005901098_1.jpg",
      category: "carte-mere",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 8,
    },
    // Processeur
    {
      name: "Intel Core i5 12600KF",
      description: "",
      brand: "",
      price: 300,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005902098_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005902098_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 9,
    },
    {
      name: "AMD Ryzen 9 5900X",
      description: "",
      brand: "",
      price: 750,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005744805_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005744805_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 10,
    },
    {
      name: "Intel Core i9 12900K",
      description: "",
      brand: "",
      price: 780,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005902107_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005902107_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 11,
    },
    {
      name: "AMD Ryzen Threadripper Pro 3995WX",
      description: "",
      brand: "",
      price: 7200,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005793719_1.jpg",
      imageDetails:
        "https://media.materiel.net/r150/products/MN0005793719_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 12,
    },
    {
      name: "Intel Core i5 12600KF",
      description: "",
      brand: "",
      price: 300,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005902098_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005902098_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 9,
    },
    {
      name: "AMD Ryzen 9 5900X",
      description: "",
      brand: "",
      price: 750,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005744805_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005744805_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 10,
    },
    {
      name: "Intel Core i9 12900K",
      description: "",
      brand: "",
      price: 780,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005902107_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005902107_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 11,
    },
    {
      name: "AMD Ryzen Threadripper Pro 3995WX",
      description: "",
      brand: "",
      price: 7200,
      countStock: 10,
      image: "https://media.materiel.net/r150/products/MN0005793719_1.jpg",
      imageDetails:
        "https://media.materiel.net/r150/products/MN0005793719_1.jpg",
      category: "processeur",
      type: "tv",
      bestSelling: true,
      newProduct: false,
      id: 12,
    },
    {
      name: 'Apple MacBook M1 Pro 16" 2022',
      description: "",
      brand: "",
      price: 2750,
      countStock: 6,
      image: "https://media.materiel.net/r150/products/MN0005902616_1.jpg",
      imageDetails:
        "https://media.materiel.net/r550/products/MN0005902616_1.jpg",
      category: "telephone",
      type: "",
      bestSelling: false,
      newProduct: true,
      id: 46,
    },
  ],
};

module.exports = products;
